### ISSUE TITLE
Support dark theme

### ISSUE THREAD

**Issue by dafonso** [SamVerschueren/alfred-font-awesome#2]
I've set my theme on macOS to mimic spotlight on dark mode. This doesn't go well with the dark font-awesome icons.

![image](https://cloud.githubusercontent.com/assets/1331773/18880220/1214552a-84cf-11e6-83a3-dbaa148d9894.png)

**Comment by SamVerschueren** [comment]
That's a valid point, I will have to ship white icons as well and select the correct icon set based upon the tint of the foreground color.

**Comment by SamVerschueren** [comment]
The code is finished for this, just waiting for the white icon set to be generated. The only thing I can't seem to fix is change the workflow icon itself. There doesn't seem to be an option in Alfred to provide a light and dark icon.

@sindresorhus Do you happen to know of a way to do that?

**Comment by SamVerschueren** [comment]
Released in `0.2.0`.
