### ISSUE TITLE
No Worky

### ISSUE THREAD

**Issue by trueschool** [SamVerschueren/alfred-font-awesome#4]
Error installing plugin. Debug log linked here: 
https://www.evernote.com/l/AAXCsWNnCj5FSa8KzXmN1DKWANamcqkaZIU

Thanks!
Ted

**Comment by SamVerschueren** [comment]
Just add the stack trace here and wrap it in 3 backticks.

**Comment by trueschool** [comment]
Thanks, I figured it out. Also, I don't know where to find the stack trace.
